server:
  port: 8080

spring:
  application:
    name: EatOr
  profiles:
    active: dev

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hezzz.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
